variables:
  name_list:
  - time
  - depth
  - DOXG
  - LDOC
  - B1
  - B2
  - NH4
  - NO3
  - PO4
  - temp
  - salinity
  - RDOC
  - LPOC
  - RPOC
  - TDIC
  - TALK
  - pH
  - pCO2
siglev_diff:
- 3.2
- 5.7
- 7.5
- 8.9
- 10.1
- 11.1
- 12.1
- 13.0
- 13.8
- 14.6
WWTP_names:
- '  Coupeville'
- '  Everett Snohomish'
- '  La Conner'
- '  Lake Stevens 002'
- '  Langley'
- '  Marysville'
- '  Mt Vernon'
- '  Mukilteo'
- '  Oak Harbor Lagoon'
- '  OF100'
- '  Penn Cove'
- '  Skagit County 2 Big Lake'
- '  Snohomish'
- '  Stanwood'
- '  Swinomish'
- '  Tulalip'
- '  Warm Beach Campground'
river_names:
- '  Skagit R_1'
- '  Skagit R_2'
- '  Snohomish R_1'
- '  Snohomish R_2'
- '  Stillaguamish R_1'
- '  Stillaguamish R_2'
- '  Whidbey east'
unique_river_names:
- Skagit
- Snohomish
- Stillaguamish
- Whidbey east
line:
  color:
    wqm_baseline: purple
    wqm_reference: teal
    deviation: royalblue
    3c: slategrey
    3l: darkslategrey
    3m: steelblue
    3n: royalblue
    3o: midnightblue
  width:
    wqm_baseline: 1.5
    wqm_reference: 1.5
    deviation: 1
    3c: 2
    3l: 2
    3m: 2
    3n: 2
    3o: 2
  style:
    wqm_baseline: solid
    wqm_reference: solid
    deviation: solid
    3l: solid
    3c: solid
    3m: dashdot
    3n: dashed
    3o: dashdot
bw_line:
  color:
    scenario: grey
    baseline: black
    reference: black
  width:
    scenario: 1.5
    baseline: 1
    reference: 1.5
  style:
    scenario: dashed
    baseline: solid
    reference: dashdot
bar:
  colors:
    DOXG: deepskyblue
    NO3: y
    NH4: darkolivegreen
region:
  colors:
    Hood: darkseagreen
    Main: mediumpurple
    SJF_Admiralty: lightsteelblue
    SOG_Bellingham: rosybrown
    South_Sound: c
    Whidbey: cornflowerblue
    ALL_REGIONS: black
paths:
  model_output:
    whidbeypers:
    - /mmfs1/gscratch/ssmc/USRS/PSI/Sukyong/kingcounty/wqm_baseline/ssm_output.nc
    - /mmfs1/gscratch/ssmc/USRS/PSI/Sukyong/kingcounty/wqm_reference/ssm_output.nc
    - /mmfs1/gscratch/ssmc/USRS/PSI/Sukyong/kingcounty/3c/ssm_output.nc
    - /mmfs1/gscratch/ssmc/USRS/PSI/Rachael/projects/KingCounty/SalishSeaModel/3l/hotstart_rdm.nc
    - /mmfs1/gscratch/ssmc/USRS/PSI/Sukyong/kingcounty/3m/ssm_output.nc
    - /mmfs1/gscratch/ssmc/USRS/PSI/Rachael/projects/KingCounty/SalishSeaModel/3n/ssm_hotstart_3n.nc
    - /mmfs1/gscratch/ssmc/USRS/PSI/Rachael/projects/KingCounty/SalishSeaModel/3o/ssm_hotstart_3o.nc
  processed_output: /mmfs1/gscratch/ssmc/USRS/PSI/Rachael/projects/KingCounty/data/
  graphics: /mmfs1/gscratch/ssmc/USRS/PSI/Rachael/projects/KingCounty/graphics/
  movies: /mmfs1/gscratch/ssmc/USRS/PSI/Rachael/projects/KingCounty/movies/
  shapefile: /mmfs1/gscratch/ssmc/USRS/PSI/Rachael/projects/KingCounty/SalishSeaModel-grid/shapefiles/SSMGrid2_tce_ecy_node_info_v2_10102022/SSMGrid2_tce_ecy_node_info_v2_10102022.shp
  nutrient_loading_inputs:
    wqm_baseline: /mmfs1/gscratch/ssmc/USRS/PSI/Sukyong/kingcounty/WQM/WQM/hotstart/inputs/ssm_pnt_wq.dat
    wqm_reference: /mmfs1/gscratch/ssmc/USRS/PSI/Sukyong/kingcounty/WQM_REF/WQM_REF/hotstart/inputs/ssm_pnt_wq.dat
    3c: /mmfs1/gscratch/ssmc/USRS/PSI/Sukyong/kingcounty/3c/inputs/ssm_pnt_wq.dat
    3l: /mmfs1/gscratch/ssmc/USRS/PSI/Rachael/projects/KingCounty/SalishSeaModel/3l/hotstart/inputs/ssm_pnt_wq.dat
    3m: /mmfs1/gscratch/ssmc/USRS/PSI/Sukyong/kingcounty/3m/inputs/ssm_pnt_wq.dat
    3n: /mmfs1/gscratch/ssmc/USRS/PSI/Rachael/projects/KingCounty/SalishSeaModel/3n/hotstart/inputs/ssm_pnt_wq.dat
    3o: /mmfs1/gscratch/ssmc/USRS/PSI/Rachael/projects/KingCounty/SalishSeaModel/3o/hotstart/inputs/ssm_pnt_wq.dat
run_information:
  run_tag:
    whidbeypers:
      wqm_baseline: 2014 Conditions
      wqm_reference: Reference
      3c: Wr1
      3l: Wr2
      3m: Wr3
      3n: Wr4
      3o: Wr5
  spin_up_days: 5
  baseline: wqm_baseline
  reference: wqm_reference
  whidbeypers_rivers:
    wqm_baseline: 2014 conditions
    wqm_reference: Reference conditions
    3c: Wr1
    3l: Wr2
    3m: Wr3
    3n: Wr4
    3o: Wr5
  run_description_short:
    whidbeypers:
      wqm_baseline: 2014 conditions
      wqm_reference: Reference
      3c: No Whidbey Rivers
      3l: 0.5x Industrial River Load
      3m: 2x 2014 River Load
      3n: No Snohomish River
      3o: 0.5x Snohomish River
