WWTP_names:
- '  Bellingham'
- '  Anacortes'
- '  Birch Bay'
- '  Blaine'
- '  Friday Harbor'
- '  Lummi Goose Pt'
- '  Whidbey Naval Station'
- '  Makah'
- '  Lummi Sandy Pt'
- '  Eastsound Water District'
- '  Roche Harbor'
- '  Fisherman Bay'
- '  Rosario Utilities'
- '  Larrabee State Park'
- '  Eastsound Orcas Village'
bar:
  colors:
    DOXG: deepskyblue
    NH4: darkolivegreen
    NO3: y
bw_line:
  color:
    baseline: black
    reference: slategrey
    scenario: grey
  style:
    baseline: solid
    reference: dashdot
    scenario: dashed
  width:
    baseline: 1
    reference: 1.5
    scenario: 2
line:
  color:
    1b_all_sog_wwtp_off: teal
    1d_small_sog_wwtp_off: darkslategrey
    1e_med_sog_wwtp_off: steelblue
    2a_sog_river_0.5times: sienna
    2b_sog_river_2times: brown
    deviation: royalblue
    wqm_baseline: darkviolet
    wqm_reference: rebeccapurple
  style:
    1b_all_sog_wwtp_off: solid
    1d_small_sog_wwtp_off: dashdot
    1e_med_sog_wwtp_off: dashed
    2a_sog_river_0.5times: dashdot
    2b_sog_river_2times: dashed
    deviation: solid
    wqm_baseline: solid
    wqm_reference: solid
  width:
    1b_all_sog_wwtp_off: 1.5
    1d_small_sog_wwtp_off: 2.0
    1e_med_sog_wwtp_off: 3.0
    2a_sog_river_0.5times: 2.0
    2b_sog_river_2times: 3.0
    deviation: 1
    wqm_baseline: 1.5
    wqm_reference: 1.5
paths:
  graphics: /mmfs1/gscratch/ssmc/USRS/PSI/Rachael/projects/KingCounty/graphics/
  model_output:
    SOG_NB:
    - /mmfs1/gscratch/ssmc/USRS/PSI/Sukyong/kingcounty/wqm_baseline/ssm_output.nc
    - /mmfs1/gscratch/ssmc/USRS/PSI/Sukyong/kingcounty/wqm_reference/ssm_output.nc
    - /mmfs1/gscratch/ssmc/USRS/PSI/Sukyong/kingcounty/1b_all_sog_wwtp_off/ssm_output.nc
    - /mmfs1/gscratch/ssmc/USRS/PSI/Sukyong/kingcounty/1c_all_sog_riv_off/ssm_output.nc
    - /mmfs1/gscratch/ssmc/USRS/PSI/Sukyong/kingcounty/1d_small_sog_wwtp_off/ssm_output.nc
    - /mmfs1/gscratch/ssmc/USRS/PSI/Sukyong/kingcounty/1e_med_sog_wwtp_off/ssm_output.nc
    - /mmfs1/gscratch/ssmc/USRS/PSI/Sukyong/kingcounty/2a_sog_river_0.5times/ssm_output.nc
    - /mmfs1/gscratch/ssmc/USRS/PSI/Sukyong/kingcounty/2b_sog_river_2times/ssm_output.nc
  movies: /mmfs1/gscratch/ssmc/USRS/PSI/Rachael/projects/KingCounty/movies/
  processed_output: /mmfs1/gscratch/ssmc/USRS/PSI/Rachael/projects/KingCounty/data/
  shapefile: /mmfs1/gscratch/ssmc/USRS/PSI/Rachael/projects/KingCounty/SalishSeaModel-grid/shapefiles/SSMGrid2_tce_ecy_node_info_v2_10102022/SSMGrid2_tce_ecy_node_info_v2_10102022.shp
region:
  colors:
    ALL_REGIONS: black
    Hood: darkseagreen
    Main: mediumpurple
    SJF_Admiralty: lightsteelblue
    SOG_Bellingham: rosybrown
    South_Sound: c
    Whidbey: cornflowerblue
river_names:
- '  Nooksack R_1'
- '  Nooksack R_2'
- '  Whatcom_Bell north'
- '  Birch Bay R'
- '  Samish_Bell south_1'
- '  Samish_Bell south_2'
- '  Orcas Island'
- '  San Juan Island'
- '  Lopez Island'
run_information:
  SOG_NB_WWTPs:
    1b_all_sog_wwtp_off: 1b
    1d_small_sog_wwtp_off: 1d
    1e_med_sog_wwtp_off: 1e
    wqm_baseline: exist
    wqm_reference: ref
  SOG_NB_rivers:
    1c_all_sog_riv_off: 1c
    2a_sog_river_0.5times: 2a
    2b_sog_river_2times: 2b
    wqm_baseline: exist
    wqm_reference: ref
  baseline: wqm_baseline
  reference: wqm_reference
  run_description:
    SOG_NB:
      1b_all_sog_wwtp_off: '1b: No SOG/NB WWTP'
      1c_all_sog_riv_off: '1c: No SOG/NB River Loading'
      1d_small_sog_wwtp_off: '1d: No SOG/NB WWTP<100'
      1e_med_sog_wwtp_off: '1e: No SOG/NB WWTP>100 (Bellingham)'
      2a_sog_river_0.5times: '2a: 0.5x River Loading in SOG/NB'
      2b_sog_river_2times: '2b: 2x River Loading in SOG/NB'
      wqm_baseline: 2014 nutrient loading
      wqm_reference: Pre-industrial nutrient loading
  run_tag:
    SOG_NB:
      1b_all_sog_wwtp_off: 1b
      1c_all_sog_riv_off: 1c
      1d_small_sog_wwtp_off: 1d
      1e_med_sog_wwtp_off: 1e
      2a_sog_river_0.5times: 2a
      2b_sog_river_2times: 2b
      wqm_baseline: Present Day
      wqm_reference: Reference
  spin_up_days: 5
siglev_diff:
- 3.2
- 5.7
- 7.5
- 8.9
- 10.1
- 11.1
- 12.1
- 13.0
- 13.8
- 14.6
stations:
  BHAM-Bay:
  - 48.767422
  - -122.575792
  Birch Bay:
  - 48.89888
  - -122.781905
  Birch Bay (Point Whitehorn):
  - 48.895273
  - -122.805067
  Cherry Point:
  - 48.868451
  - -122.7804
  Eastsound:
  - 48.684406
  - -122.898953
  Quartermaster Harbor:
  - 47.3793
  - -122.462
  Se'lhaemNOAA_46118:
  - 48.724
  - -122.576
variables:
  name_list:
  - time
  - depth
  - DOXG
  - LDOC
  - B1
  - B2
  - NH4
  - NO3
  - PO4
  - temp
  - salinity
  - RDOC
  - LPOC
  - RPOC
  - TDIC
  - TALK
  - pH
  - pCO2
