line_colors:
  1b_all_sog_wwtp_off: teal
  1c_all_sog_riv_off: darkgoldenrod
  1d_small_sog_wwtp_off: darkslategrey
  1e_med_sog_wwtp_off: lightseagreen
  2a_sog_river_0.5times: sienna
  2b_sog_river_2times: brown
  deviation: royalblue
  wqm_baseline: darkviolet
paths:
  graphics: /mmfs1/gscratch/ssmc/USRS/PSI/Rachael/projects/KingCounty/graphics/
  model_output:
  - /mmfs1/gscratch/ssmc/USRS/PSI/Sukyong/kingcounty/wqm_baseline/ssm_output.nc
  - /mmfs1/gscratch/ssmc/USRS/PSI/Sukyong/kingcounty/1b_all_sog_wwtp_off/ssm_output.nc
  - /mmfs1/gscratch/ssmc/USRS/PSI/Sukyong/kingcounty/1c_all_sog_riv_off/ssm_output.nc
  - /mmfs1/gscratch/ssmc/USRS/PSI/Sukyong/kingcounty/1d_small_sog_wwtp_off/ssm_output.nc
  - /mmfs1/gscratch/ssmc/USRS/PSI/Sukyong/kingcounty/1e_med_sog_wwtp_off/ssm_output.nc
  - /mmfs1/gscratch/ssmc/USRS/PSI/Sukyong/kingcounty/2a_sog_river_0.5times/ssm_output.nc
  - /mmfs1/gscratch/ssmc/USRS/PSI/Sukyong/kingcounty/2b_sog_river_2times/ssm_output.nc
  processed_output: /mmfs1/gscratch/ssmc/USRS/PSI/Rachael/projects/KingCounty/data/
  shapefile: /mmfs1/gscratch/ssmc/USRS/PSI/Rachael/projects/KingCounty/KingCounty-Rachael/kevin_shapefiles/SSMGrid2_062822/SSMGrid2_062822.shp
run_index:
  0.5x SOG/NB River Loading: 5
  2.0x SOG/NB River Loading: 6
  Baseline: 0
  No BNR<100 WWTP: 3
  No BNR>100 WWTP: 4
  No SOG/NB River Loading: 2
  No SOG/NB WWTP: 1
run_information:
  baseline: wqm_baseline
  run_description:
    1b_all_sog_wwtp_off: '1b: No SOG/NB WWTP'
    1c_all_sog_riv_off: '1c: No SOG/NB River Loading'
    1d_small_sog_wwtp_off: '1d: No SOG/NB WWTP<100'
    1e_med_sog_wwtp_off: '1e: No SOG/NB WWTP>100'
    2a_sog_river_0.5times: '2a: 0.5x(River Loading)

      in SOG/NB'
    2b_sog_river_2times: '2b: 2.0x(River Loading)

      in SOG/NB'
    wqm_baseline: Baseline
  run_tag:
    1b_all_sog_wwtp_off: 1b
    1c_all_sog_riv_off: 1c
    1d_small_sog_wwtp_off: 1d
    1e_med_sog_wwtp_off: 1e
    2a_sog_river_0.5times: 2a
    2b_sog_river_2times: 2b
    wqm_baseline: Baseline
run_tag:
  0p5x_SOGNB_RiverLoading: 5
  2p0x_SOGNB_RiverLoading: 6
  Baseline: 0
  No_SOGNB_RiverLoading: 2
  No_SOGNB_WWTP: 1
  No_gt100_WWTP: 4
  No_lt100_WWTP: 3
siglev_diff:
- 3.2
- 5.7
- 7.5
- 8.9
- 10.1
- 11.1
- 12.1
- 13.0
- 13.8
- 14.6
variables:
  model_tags:
    DO: Var_10
    NH3: Var_14
    NO3: Var_15
    NPP: Var_17
    Salinity: Var_19
    Temp: Var_18
  name_list:
  - time
  - depth
  - DOXG
  - LDOC
  - B1
  - B2
  - NH4
  - NO3
  - PO4
  - temp
  - salinity
  - RDOC
  - LPOC
  - RPOC
  - TDIC
  - TALK
  - pH
  - pCO2
